import express from 'express';
import swaggerUi from 'swagger-ui-express';
import swaggerJSDoc from 'swagger-jsdoc';
import dotenv from 'dotenv';
import { Request, Response } from 'express';
import swaggerModelValidator from "swagger-model-validator";

dotenv.config();
const port = process.env.PORT;

const router = express.Router();

const oprions: swaggerJSDoc.Options = {
    swaggerDefinition: {
        openapi: '3.0.0',
        info: {
            title: 'API Documentation',
            version: '1.0.0',
            description: 'API documentation generated by swagger-jsdoc and served with swagger-ui-express',
        },
        tags: [
            {
                name: 'Users',
                description: 'Endpoints for managing users',
            },
            {
                name: 'Products',
                description: 'Endpoints for managing products',
            },
        ],
        servers: [
            {
                url: `http://localhost:${port}`,
                description: 'Development server',
            },
        ],
        components: {
            securitySchemes: {
                BearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'JWT',
                    description: 'Enter your bearer token in the format **Bearer &lt;token&gt;**',
                },
                ApiKeyAuth: {
                    type: 'apiKey',
                    in: 'header',
                    name: 'x-api-key',
                    description: 'API Key needed to access the endpoints',
            },
        },
    

    }
},
    apis: ['./src/routes/user.routes/*.ts'], // Path to the API docs
};

const swaggerSpec = swaggerJSDoc(oprions);

swaggerModelValidator(swaggerSpec as any);

router.get('/json', (req: Request, res: Response) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
});

router.use('/', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
export default router;